version: '3'

services:
  postgres-prisma:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: node_prisma
    ports:
      - 6532:5432
  nodejs:
    build: .
    container_name: nodejs
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - postgres_prisma
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres_prisma/node_prisma?schema=public&sslmode=prefer&&connection_limit=10
      JWT_SECRET_KEY: SECRET_KEY
      PORT: 8000
